var initState = {
    userInfo:{},//用户登录的信息
    currentMenu:{},//当前选择的菜单
    openMenuidList:[],//当前已经打开的菜单,//主要是防止资源上来就加载
    leftContentState:{'show':false,'left':-297},//左边leftContent默认状态(不显示,缩进)
    isShowMIdContent:false,//是否需要显示中间
    isShowUI:true,//是否显示左边中间和菜单栏
    isShowMIdContentByLeft:true,//是否需要显示中间通过左边按钮控制
    isBGcolor:false,//是否显示背景色以及控制地图背景颜色
    isShowHryj:true,//是否默认开启呼入预警
    currentMapLevel:"",//当前地图的层级
    currentMapType:"2D",//当前地图类型（3D或者2D）
    currentJlTypes:[],//当前选取展示的的警力类型
    showYbssDiv:false,//是否显示疫情防控模块
    jq:{
      search:{}//警情的搜索条件
    },
    jl:{
      search:{}//警力的搜索条件
    },
    zzry:{//组织人员
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    ajzc:{//案件侦查
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    qqfw:{//请求服务
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    swxx:{//涉稳信息
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    yyjq:{//扬言警情
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    zlhc:{//指令核查
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    xxkb:{//信息快报
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    yagl:{//预案管理
      currentPlan:{},//当前选择预案
    },
    ryhc:{//人员核查
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    cfjf:{//重复纠纷
      currentDept:{},//当前选择的部门
      searchName:{},//搜索的名称
      allDeptListObj:{}//部门列表树
    },
    jsgl:{//角色管理
      currentDept:{},//当前选择的部门
      allDeptListObj:{}//部门列表树
    },
    gpsgl:{//GPS管理
      currentDept:{},//当前选择的部门
      allDeptListObj:{}//部门列表树
    },
    dkkd:{//堵控卡点
      currentDept:{},//当前选择的部门
      allDeptListObj:{}//部门列表树
    },
    zpyp:{//照片云盘
      currentDept:{},//当前选择的部门
      allDeptListObj:{},//部门列表树
      pictureUrlRecords:[]//照片的预览列表
    },
    jqfx:{//警情分析
      currentDept:{},//当前选择的部门
      allDeptListObj:{},//部门列表树
    },
    jqbb:{//警情报表
      currentDept:{},//当前选择的部门
      allDeptListObj:{},//部门列表树
    },
    jqtj:{//警情统计
      currentDept:{},//当前选择的部门
      allDeptListObj:{},//部门列表树
    },
    djda:{//盯警盯案
      currentDept:{},//当前选择的部门
      allDeptListObj:{},//部门列表树
    },
    czlog:{//操作日志
      currentDept:{},//当前选择的部门
      allDeptListObj:{}//部门列表树
    },
    zdry:{//重点人员
      currentDept:{},//当前选择的部门
      allDeptListObj:{}//部门列表树
    },
    hctj:{//核查统计
      countObj:{},//统计数据
    },
    ssyj:{
      yxjqList:[],//有效警情
      xsjqList:[],//刑事警情
      zajqList:[],//治安警情
      twzpjqList:[],//通网诈骗警情
    },
    jqzl:{//警情质量
      currentDept:{},//当前选择的部门
      allDeptListObj:{}//部门列表树
    },
    zpxa:{//诈骗小案
      currentDept:{},//当前选择的部门
      allDeptListObj:{}//部门列表树
    },
    mrtb:{
      currentDate:"",//当前日期
    },
    bxgc:{
      currentMonth:"",//当前月份
    },
    chat:{
      unReadMap:{}
    },
    push:{
      ssjq:{},
      chat:{},
      ssjl:{},
      hryj:{},
      dkkd:{},
      bkyj:{},
      xfyj:{},
      ckyj:{},
    }
};

export default{
    initState: initState
}